# Generated by Django 3.2.25 on 2025-02-16 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_dietarytracking_mealplan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nutritionalinformation',
            old_name='nutritional_info_id',
            new_name='nutritional_id',
        ),
        migrations.AddField(
            model_name='nutritionalinformation',
            name='is_ai_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='nutritionalinformation',
            name='calories',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='nutritionalinformation',
            name='carbohydrates',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='nutritionalinformation',
            name='fat',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='nutritionalinformation',
            name='fiber',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='nutritionalinformation',
            name='protein',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='nutritionalinformation',
            name='recipe_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutritional_info', to='recipe.recipe'),
        ),
        migrations.AlterField(
            model_name='nutritionalinformation',
            name='sugar',
            field=models.FloatField(default=0),
        ),
        migrations.AlterModelTable(
            name='nutritionalinformation',
            table='nutritional_information',
        ),
    ]
