# Generated by Django 3.2.25 on 2025-02-19 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_auto_20250216_2358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nutritionalinformation',
            name='recipe_id',
        ),
        migrations.AddField(
            model_name='event',
            name='instructor_bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='instructor_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='prerequisites',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='schedule',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nutritionalinformation',
            name='recipe',
            field=models.OneToOneField(db_column='recipe_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nutritional_info', to='recipe.recipe'),
        ),
    ]
