# Generated by Django 3.2.25 on 2024-10-14 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='user_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
