# Generated by Django 3.2.25 on 2025-03-10 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_auto_20250219_1209'),
    ]

    operations = [
        migrations.CreateModel(
            name='DietaryGuideline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(choices=[('diabetic', 'Diabetic'), ('cholesterol', 'High Cholesterol'), ('blood_pressure', 'High Blood Pressure'), ('heart_disease', 'Heart Disease'), ('kidney_disease', 'Kidney Disease'), ('celiac', 'Celiac Disease')], max_length=50)),
                ('nutrient', models.CharField(max_length=50)),
                ('min_value', models.FloatField()),
                ('max_value', models.FloatField()),
                ('unit', models.CharField(max_length=10)),
                ('description', models.TextField()),
                ('recommendations', models.TextField()),
            ],
            options={
                'unique_together': {('condition', 'nutrient')},
            },
        ),
    ]
