# Generated by Django 3.2.25 on 2024-08-27 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_alter_customuser_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipename', models.CharField(max_length=200, null=True)),
                ('ingredients', models.TextField(max_length=200, null=True)),
                ('instructions', models.TextField(max_length=200, null=True)),
                ('image', models.ImageField(upload_to='\\media')),
                ('tags', models.TextField(max_length=200, null=True)),
                ('nutritionalInfo', models.TextField(max_length=200, null=True)),
                ('category', models.TextField(max_length=200, null=True)),
                ('ratings', models.IntegerField()),
            ],
        ),
    ]
