# Generated by Django 3.2.25 on 2024-08-28 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0006_auto_20240828_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.TextField(max_length=700, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='instructions',
            field=models.TextField(max_length=700, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='nutritionalInfo',
            field=models.TextField(max_length=700, null=True),
        ),
    ]
