# Generated by Django 3.2.25 on 2025-01-27 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0006_favorite'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeAllergen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_id', models.IntegerField()),
                ('allergen_name', models.CharField(choices=[('dairy', 'Dairy'), ('eggs', 'Eggs'), ('nuts', 'Tree Nuts'), ('peanuts', 'Peanuts'), ('shellfish', 'Shellfish'), ('wheat', 'Wheat'), ('soy', 'Soy'), ('fish', 'Fish'), ('gluten', 'Gluten'), ('sesame', 'Sesame')], max_length=50)),
                ('severity', models.CharField(choices=[('contains', 'Contains'), ('may_contain', 'May Contain'), ('traces', 'Traces')], max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'recipe_allergens',
                'unique_together': {('recipe_id', 'allergen_name')},
            },
        ),
    ]
