# Generated by Django 3.2.25 on 2025-02-02 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0008_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='category_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='image_category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
