# Generated by Django 3.2.25 on 2024-08-31 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0008_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='mobile',
        ),
    ]
