# Generated by Django 3.2.25 on 2025-02-04 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0008_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='contact_email',
            field=models.EmailField(default='example@email.com', max_length=254),
        ),
        migrations.AddField(
            model_name='event',
            name='contact_phone',
            field=models.CharField(default='1234567890', max_length=15),
        ),
        migrations.AddField(
            model_name='event',
            name='duration_hours',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='event',
            name='duration_minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(
                choices=[
                    ('cooking_class', 'Cooking Class'),
                    ('workshop', 'Workshop'),
                    ('tasting', 'Food Tasting'),
                    ('competition', 'Cooking Competition'),
                    ('seminar', 'Culinary Seminar')
                ],
                default='workshop',
                max_length=50
            ),
        ),
        migrations.AddField(
            model_name='event',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
