# Generated by Django 3.2.25 on 2024-10-20 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0008_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='subcategory_id',
            field=models.IntegerField(null=True),
        ),
    ]
