# Generated by Django 3.2.25 on 2024-08-31 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0009_remove_customuser_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='instructions',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
