# Generated by Django 3.2.25 on 2025-02-03 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0009_auto_20250204_0145'),
    ]

    operations = [
    ]
