# Generated by Django 3.2.25 on 2024-10-23 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0010_category_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='servings',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='timing',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
